# Generated by Django 3.0.6 on 2020-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_filename', models.CharField(max_length=200)),
                ('published_Date', models.DateTimeField(blank=True, null=True)),
                ('cv_File', models.FileField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
