# Generated by Django 3.0.6 on 2020-06-16 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_Title', models.CharField(max_length=200)),
                ('post_Text', models.TextField()),
                ('post_Type', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Art', 'Art'), ('Other', 'Other')], default='other', max_length=16)),
                ('post_Assignment', models.BooleanField(default=False)),
                ('published_Date', models.DateTimeField(blank=True, null=True)),
                ('post_Image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('post_Body_Image1', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('post_Body_Image2', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('post_Body_Image3', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('post_Body_Image4', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('post_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
