# Generated by Django 3.0.6 on 2020-06-16 16:58

import apps.aboutme.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_Name', models.CharField(max_length=200)),
                ('attribute_Level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_Title', models.CharField(max_length=200)),
                ('institute_Name', models.CharField(max_length=200)),
                ('year_Gained', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), apps.aboutme.models.max_value_current_year])),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('degree_completed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_Name', models.CharField(max_length=200)),
                ('equipment_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_Name', models.CharField(max_length=100)),
                ('my_Level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('my_Introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_Title', models.CharField(max_length=200)),
                ('skill_Description', models.TextField()),
                ('skill_Level', models.CharField(choices=[('Beginner', 'Beginner'), ('Average', 'Average'), ('Skilled', 'Skilled'), ('Specialist', 'Specialist'), ('Expert', 'Expert')], default='Beginner', max_length=16)),
                ('skill_Type', models.CharField(choices=[('Script or Programming Languages', 'Script or Programming Languages'), ('Other', 'Other')], default='Other', max_length=90)),
                ('year_Started', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), apps.aboutme.models.max_value_current_year])),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_Exp_Title', models.CharField(max_length=200)),
                ('work_Exp_Company', models.CharField(max_length=200)),
                ('work_Exp_Description', models.TextField()),
                ('year_Started', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), apps.aboutme.models.max_value_current_year])),
                ('year_Finished', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), apps.aboutme.models.max_value_current_year])),
                ('published_Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
